
export function generateFlagIconUrl(flag) {
  if (flag in currencies && currencies[flag].img.length > 0) {
    return `${import.meta.env.BASE_URL}flags/${flag.toLowerCase()}.png`;
  }

  return false;
}

export const currencies = {
  aed: { label: 'Dirham dos Emirados Árabes Unidos', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/23px-Flag_of_the_United_Arab_Emirates.svg.pnimg: g', },
  ars: { label: 'Peso argentino', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/23px-Flag_of_Argentina.svg.pnimg: g', },
  aud: { label: 'Dólar australiano', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/23px-Flag_of_Australia_%28converted%29.svg.pnimg: g', },
  bch: { label: 'Bitcoin Cash', img: '', },
  bdt: { label: 'Taka de Bangladesh', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.pnimg: g', },
  bhd: { label: 'Dinar do Bahrein', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/23px-Flag_of_Bahrain.svg.pnimg: g', },
  bmd: { label: 'Dólar das Bermudas', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/23px-Flag_of_Bermuda.svg.pnimg: g', },
  bnb: { label: 'Binance Coin', img: '', },
  brl: { label: 'Real brasileiro', img: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/22px-Flag_of_Brazil.svg.pnimg: g', },
  btc: { label: 'Bitcoin', img: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png?169650140img: 0', },
  cad: { label: 'Dólar canadense', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/23px-Flag_of_Canada_%28Pantone%29.svg.pnimg: g', },
  chf: { label: 'Franco suíço', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/16px-Flag_of_Switzerland_%28Pantone%29.svg.pnimg: g', },
  clp: { label: 'Peso chileno', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/23px-Flag_of_Chile.svg.pnimg: g', },
  cny: { label: 'Yuan chinês', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.pnimg: g', },
  czk: { label: 'Coroa tcheca', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/23px-Flag_of_the_Czech_Republic.svg.pnimg: g', },
  dkk: { label: 'Coroa dinamarquesa', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/20px-Flag_of_Denmark.svg.pnimg: g', },
  dot: { label: 'Polkadot', img: '', },
  eos: { label: 'EOS.IO', img: '', },
  eth: { label: 'Ethereum', img: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png?169650162img: 8', },
  eur: { label: 'Euro', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/23px-Flag_of_Europe.svg.pnimg: g', },
  gbp: { label: 'Libra esterlina', img: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.pnimg: g', },
  gel: { label: 'Lari georgiano', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/23px-Flag_of_Georgia.svg.pnimg: g', },
  hkd: { label: 'Dólar de Hong Kong', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/23px-Flag_of_Hong_Kong.svg.pnimg: g', },
  huf: { label: 'Forint húngaro', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/23px-Flag_of_Hungary.svg.pnimg: g', },
  idr: { label: 'Rupia indonésia', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/23px-Flag_of_Indonesia.svg.pnimg: g', },
  ils: { label: 'Novo shekel israelense', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/21px-Flag_of_Israel.svg.pnimg: g', },
  inr: { label: 'Rupia indiana', img: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.pnimg: g', },
  jpy: { label: 'Iene japonês', img: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/23px-Flag_of_Japan.svg.pnimg: g', },
  krw: { label: 'Won sul-coreano', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/23px-Flag_of_South_Korea.svg.pnimg: g', },
  kwd: { label: 'Dinar kuwaitiano', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/23px-Flag_of_Kuwait.svg.pnimg: g', },
  lkr: { label: 'Rupia do Sri Lanka', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/23px-Flag_of_Sri_Lanka.svg.pnimg: g', },
  ltc: { label: 'Litecoin', img: '', },
  mmk: { label: 'Kyat de Myanmar', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/23px-Flag_of_Myanmar.svg.pnimg: g', },
  mxn: { label: 'Peso mexicano', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/23px-Flag_of_Mexico.svg.pnimg: g', },
  myr: { label: 'Ringgit malaio', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/23px-Flag_of_Malaysia.svg.pnimg: g', },
  ngn: { label: 'Naira nigeriana', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/23px-Flag_of_Nigeria.svg.pnimg: g', },
  nok: { label: 'Coroa norueguesa', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/21px-Flag_of_Norway.svg.pnimg: g', },
  nzd: { label: 'Dólar da Nova Zelândia', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/21px-Flag_of_Norway.svg.pnimg: g', },
  php: { label: 'Peso filipino', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/23px-Flag_of_the_Philippines.svg.pnimg: g', },
  pkr: { label: 'Rupia paquistanesa', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/23px-Flag_of_Pakistan.svg.pnimg: g', },
  pln: { label: 'Złoty polonês', img: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/23px-Flag_of_Poland.svg.pnimg: g', },
  rub: { label: 'Rublo russo', img: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/23px-Flag_of_Russia.svg.pnimg: g', },
  sar: { label: 'Riyal saudita', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/23px-Flag_of_Saudi_Arabia.svg.pnimg: g', },
  sek: { label: 'Coroa sueca', img: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/23px-Flag_of_Sweden.svg.pnimg: g', },
  sgd: { label: 'Dólar de Singapura', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/23px-Flag_of_Singapore.svg.pnimg: g', },
  thb: { label: 'Baht tailandês', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/23px-Flag_of_Thailand.svg.pnimg: g', },
  try: { label: 'Lira turca', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/23px-Flag_of_Turkey.svg.pnimg: g', },
  twd: { label: 'Novo dólar taiwanês', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/23px-Flag_of_the_Republic_of_China.svg.pnimg: g', },
  uah: { label: 'Hryvnia ucraniano', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/23px-Flag_of_Ukraine.svg.pnimg: g', },
  usd: { label: 'Dólar americano', img: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.pnimg: g', },
  vef: { label: 'Bolívar venezuelano', img: '', },
  vnd: { label: 'Dong vietnamita', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/23px-Flag_of_Vietnam.svg.pnimg: g', },
  xag: { label: 'Prata (1 onça troy)', img: '', },
  xau: { label: 'Ouro (1 onça troy)', img: '', },
  xdr: { label: 'Direitos Especiais de Saque do FMI', img: '', },
  xlm: { label: 'Lumen', img: '', },
  xrp: { label: 'XRP', img: '', },
  yfi: { label: 'Yearn.finance', img: '', },
  zar: { label: 'Rand sul-africano', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/23px-Flag_of_Eswatini.svg.pnimg: g', },
  bits:{ label: 'Bits (unidade de bitcoin)', img: '', },
  link:{ label: 'Chainlink', img: '', },
  sats:{ label: '', img: '', },
}
